# Execution Service - Standalone Configuration
# Run independently: cd execution_service && docker-compose up

services:
  execution-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peerprep_execution_service
    ports:
      - "${EXECUTION_SERVICE_PORT:-8007}:8000"
    environment:
      - DEBUG=${DEBUG:-true}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,execution-service}
      - JUDGE0_URL=${JUDGE0_URL:-https://ce.judge0.com}
      - JUDGE0_API_KEY=${JUDGE0_API_KEY:-your-api-key-here}
      - QUESTION_SERVICE_URL=${QUESTION_SERVICE_URL:-http://question-service:8000}
    volumes:
      - ./:/app:rw
    networks:
      - shared_network
      - execution_network
    # No dependencies needed for cloud Judge0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Using Judge0 Cloud Service - no local services needed

networks:
  shared_network:
  execution_network:
    driver: bridge
    name: peerprep_execution_network


