# Frontend Service - Standalone Configuration
# Run independently: cd frontend && docker-compose up

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peerprep_frontend
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    environment:
      - NODE_ENV=${ENVIRONMENT:-development}
      - VITE_QUESTION_SERVICE_URL=http://question_service:8000
      - VITE_MATCHING_SERVICE_URL=http://matching_service:8000
      - VITE_HISTORY_SERVICE_URL=http://history_service:8000
      - VITE_USER_SERVICE_URL=http://user_service:8000
      - VITE_COLLABORATION_SERVICE_URL=http://collaboration_service:8000
      - VITE_CHAT_SERVICE_URL=http://chat_service:8000
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - /app/node_modules
    networks:
      - shared_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  shared_network:
    external: true
    name: peerprep_shared_network
