# Generated by Django 5.2.6 on 2025-10-07 09:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('collaborator_id', models.UUIDField()),
                ('session_id', models.UUIDField()),
                ('question_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='history_his_user_id_046448_idx'), models.Index(fields=['collaborator_id'], name='history_his_collabo_5c252c_idx'), models.Index(fields=['question_id'], name='history_his_questio_28df0a_idx'), models.Index(fields=['created_at'], name='history_his_created_2782f5_idx')],
            },
        ),
    ]
