"""update session metadata table

Revision ID: 4d454ab0e9a1
Revises: e82c36e630e0
Create Date: 2025-11-02 13:20:06.783886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4d454ab0e9a1'
down_revision: Union[str, Sequence[str], None] = 'e82c36e630e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessionmetadata', sa.Column('question_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('sessionmetadata', sa.Column('question_statement_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('sessionmetadata', sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('sessionmetadata', sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('sessionmetadata', sa.Column('company_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('sessionmetadata', 'attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessionmetadata', sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sessionmetadata', 'company_tags')
    op.drop_column('sessionmetadata', 'difficulty')
    op.drop_column('sessionmetadata', 'topics')
    op.drop_column('sessionmetadata', 'question_statement_md')
    op.drop_column('sessionmetadata', 'question_title')
    # ### end Alembic commands ###
