# Generated by Django 5.2.6 on 2025-10-07 10:17

from django.db import migrations


def sync_users_to_allauth(apps, schema_editor):  # pylint: disable=unused-argument
    """
    Create EmailAddress entries for all existing users.

    This ensures that existing users in the database have corresponding
    EmailAddress records in allauth's system.
    """
    User = apps.get_model('users', 'User')
    EmailAddress = apps.get_model('account', 'EmailAddress')

    users = User.objects.all()

    for user in users:
        # Create EmailAddress entry if it doesn't exist
        EmailAddress.objects.get_or_create(
            user=user,
            email=user.email,
            defaults={
                'verified': user.is_verified,
                'primary': True,
            }
        )


def reverse_sync(apps, schema_editor):  # pylint: disable=unused-argument
    """
    Reverse migration: remove EmailAddress entries for users.

    This is a no-op as we don't want to delete verification data.
    """
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_usersessionprofile_delete_usersession_and_more'),
        ('account', '__first__'),  # Ensure allauth tables exist
    ]

    operations = [
        migrations.RunPython(sync_users_to_allauth, reverse_sync),
    ]
