# Generated by Django 5.2.6 on 2025-10-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.JSONField(default=list, help_text='List of problem constraints'),
        ),
        migrations.AddField(
            model_name='question',
            name='examples',
            field=models.JSONField(default=list, help_text='List of input/output examples'),
        ),
    ]
