# Generated by Django 5.2.6 on 2025-09-26 16:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the session profile', primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(help_text='Hashed refresh token for JWT', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the session', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('login_at', models.DateTimeField(auto_now_add=True, help_text='When the user logged in')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Last activity timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is active')),
                ('session', models.OneToOneField(help_text='Django session associated with this profile', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='sessions.session')),
                ('user', models.ForeignKey(help_text='User associated with this session', on_delete=django.db.models.deletion.CASCADE, related_name='session_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session Profile',
                'verbose_name_plural': 'User Session Profiles',
                'db_table': 'user_session_profiles',
            },
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.AddIndex(
            model_name='usersessionprofile',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_2fd553_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessionprofile',
            index=models.Index(fields=['login_at'], name='user_sessio_login_a_4b7776_idx'),
        ),
        migrations.AddIndex(
            model_name='usersessionprofile',
            index=models.Index(fields=['last_activity_at'], name='user_sessio_last_ac_a8dd23_idx'),
        ),
    ]
